theme: minima
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Predicting the cause of Power Outages in United States
description: > # this means to ignore newlines until "baseurl:"
  Built for DSC 80 @ UCSD.

author: Saarth Shah and Saathvik Dirisala